<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Ahmad-AbuAli" failures="1" tests="7" name="P01_Testcases.TC06_SendBoukiWallet" time="42.288" errors="0" timestamp="2023-05-30T17:10:17 AST" skipped="3">
  <testcase classname="P01_Testcases.TC06_SendBoukiWallet" name="Start_And_Enter_Number" time="11.076">
    <skipped/>
  </testcase> <!-- Start_And_Enter_Number -->
  <system-out/>
  <testcase classname="P01_Testcases.TC06_SendBoukiWallet" name="Close_Device_Pop_Up" time="10.855">
    <skipped/>
  </testcase> <!-- Close_Device_Pop_Up -->
  <system-out/>
  <testcase classname="P01_Testcases.TC06_SendBoukiWallet" name="Enter_OTP" time="1.104">
    <skipped/>
  </testcase> <!-- Enter_OTP -->
  <system-out/>
  <testcase classname="P01_Testcases.TC06_SendBoukiWallet" name="Enter_Password" time="6.888"/>
  <system-out/>
  <testcase classname="P01_Testcases.TC06_SendBoukiWallet" name="Open_Send_Money_Options" time="2.491"/>
  <system-out/>
  <testcase classname="P01_Testcases.TC06_SendBoukiWallet" name="Bouki_Wallet" time="1.095"/>
  <system-out/>
  <testcase classname="P01_Testcases.TC06_SendBoukiWallet" name="Choose_Contact" time="8.779">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at P03_Screens.C07_SendMoneyScreen.ChooseContact(C07_SendMoneyScreen.java:38)
at P01_Testcases.TC06_SendBoukiWallet.Choose_Contact(TC06_SendBoukiWallet.java:68)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Choose_Contact -->
  <system-out/>
</testsuite> <!-- P01_Testcases.TC06_SendBoukiWallet -->
